apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "dislog.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "dislog.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{ include "dislog.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "dislog.fullname" . }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      name: {{ include "dislog.fullname" . }}
      labels: {{ include "dislog.labels" . | nindent 8 }}
    spec:
      initContainers:
        - name: {{ include "dislog.fullname" . }}-config-init
          image: busybox
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |-
              ID=$(echo $HOSTNAME | rev | cut -d- -f1 | rev)
              cat > /var/run/dislog/config.yaml <<EOD
              data-dir: /var/run/dislog/data
              rpc-port: {{.Values.rpcPort}}
              bind-addr: "$HOSTNAME.dislog.{{.Release.Namespace}}.svc.cluster.local:{{.Values.serfPort}}"
              bootstrap: $([ $ID = 0 ] && echo true || echo false)
              $([ $ID != 0 ] && echo 'start-join-addrs: "dislog-0.dislog.{{.Release.Namespace}}.svc.cluster.local:{{.Values.serfPort}}"')
              EOD
          volumeMounts:
            - name: datadir
              mountPath: /var/run/dislog
      containers:
        - name: {{ include "dislog.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.rpcPort }}
              name: rpc
            - containerPort: {{ .Values.serfPort }}
              name: serf
          args:
            - --config-file=/var/run/dislog/config.yaml
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - |-
                /bin/grpc_health_probe -addr=$HOSTNAME.dislog.{{.Release.Namespace}}.svc.cluster.local:{{.Values.rpcPort}}
            initialDelaySeconds: 10
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - |-
                /bin/grpc_health_probe -addr=$HOSTNAME.dislog.{{.Release.Namespace}}.svc.cluster.local:{{.Values.rpcPort}}
            initialDelaySeconds: 10
          volumeMounts:
            - name: datadir
              mountPath: /var/run/dislog
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.storage }}
